services:
  - type: web
    name: warfare-c2
    runtime: python
    repo: https://github.com/seefile/warfare-c2
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y build-essential python3-dev
      apt-get install -y libssl-dev libffi-dev
      apt-get install -y libpcap-dev
      apt-get install -y libusb-1.0-0-dev
      apt-get install -y portaudio19-dev
      apt-get install -y wget curl git
      apt-get install -y xvfb x11-utils
      apt-get install -y chromium chromium-driver
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn warfare_c2:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONHASHSEED
        value: random
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /ping
    autoDeploy: true
    plan: free
